- name: Install package apache2
  action: apt pkg=apache2 state=present

- name: write apache2 security related config file
  action: copy src=security dest=/etc/apache2/conf.d/security
             owner=root group=root mode=0644
  notify:
    - restart apache

- name: Install directory config for robots.txt directory
  template: src=robots.j2 dest=/etc/apache2/conf.d/robots
  notify:
    - restart apache

- name: Write apache2.conf
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
            owner=root group=root mode=0644
  notify: restart apache

- name: Write ports.conf
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
            owner=root group=root mode=0644
  notify: restart apache

# Set apache and regular user umask to 002 in order to make use of user private
# groups for sharing access to directories.
# TODO: Depend on group_sharing_perms or a common var in group_vars?
- name: write apache2 envvars
  action: copy src=../files/envvars dest=/etc/apache2/envvars
             owner=root group=root mode=0644
  notify:
    - restart apache

# Activate a number of Apache modules.
- file: state=link src=/etc/apache2/mods-available/{{item}} path=/etc/apache2/mods-enabled/{{item}}
  with_items:
   - rewrite.load
  notify:
   - restart apache


- name: Ensure apache is running
  action: service name=apache2 state=running
